# Generated by Django 3.0.8 on 2020-08-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200820_1522'),
        ('travel', '0003_auto_20200820_1121'),
    ]

    operations = [
    ]
