# Generated by Django 3.0.8 on 2020-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200820_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/tours/3'),
        ),
    ]
