# Generated by Django 3.0.8 on 2020-08-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_merge_20200821_0756'),
        ('travel', '0004_auto_20200824_0804'),
    ]

    operations = [
    ]
