# Generated by Django 3.1 on 2020-08-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_merge_20200824_0927'),
        ('travel', '0005_auto_20200823_1639'),
    ]

    operations = [
    ]
