# Generated by Django 3.1 on 2020-08-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20200825_1044'),
        ('travel', '0006_merge_20200825_0806'),
    ]

    operations = [
    ]
