# Generated by Django 3.0.8 on 2020-08-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20200825_1044'),
        ('travel', '0005_auto_20200823_1639'),
    ]

    operations = [
    ]
