# Generated by Django 3.1 on 2020-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_merge_20200826_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/reviews'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(help_text='One word about your trip !', max_length=100),
        ),
    ]
