# Generated by Django 3.0.8 on 2020-08-26 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_merge_20200825_0806'),
        ('travel', '0009_auto_20200825_1430'),
    ]

    operations = [
    ]
