# Generated by Django 3.0.8 on 2020-08-26 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_merge_20200826_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
