# Generated by Django 3.1 on 2020-08-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20200826_0953'),
        ('travel', '0008_merge_20200825_1425'),
        ('travel', '0011_follower_date_added'),
    ]

    operations = [
    ]
