# Generated by Django 3.1 on 2020-08-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_merge_20200826_1437'),
        ('travel', '0008_merge_20200825_1425'),
    ]

    operations = [
    ]
