# Generated by Django 3.0.3 on 2020-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_merge_20200827_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/tours/2'),
        ),
    ]
