# Generated by Django 3.0.3 on 2020-08-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0013_auto_20200830_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_model_id', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.IntegerField(choices=[(1, 'Folow'), (2, 'Unfolow'), (3, 'Updatebooking')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'Seen'), (2, 'Unseen')], default=1)),
                ('action_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_create_notification', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_has_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
