# Generated by Django 3.0.3 on 2020-08-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen')], default=1),
        ),
    ]
