# Generated by Django 3.0.3 on 2020-08-27 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0014_auto_20200827_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Tour'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together={('tour', 'user')},
        ),
    ]
