# Generated by Django 3.0.3 on 2020-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20200827_1532'),
        ('travel', '0012_merge_20200827_0825'),
    ]

    operations = [
    ]
