# Generated by Django 3.1 on 2020-08-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_activity'),
        ('travel', '0016_merge_20200828_1312'),
    ]

    operations = [
    ]
