# Generated by Django 3.1 on 2020-08-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_merge_20200828_1312'),
        ('travel', '0013_merge_20200827_1142'),
    ]

    operations = [
    ]
