# Generated by Django 3.1 on 2020-08-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_merge_20200831_1102'),
        ('travel', '0017_merge_20200829_1630'),
    ]

    operations = [
    ]
