# Generated by Django 3.0.3 on 2020-08-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_merge_20200829_1630'),
        ('travel', '0015_auto_20200830_2255'),
    ]

    operations = [
    ]
