# Generated by Django 3.0.3 on 2020-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_merge_20200831_1449'),
        ('travel', '0018_merge_20200831_1417'),
    ]

    operations = [
    ]
