# Generated by Django 3.1 on 2020-09-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_merge_20200831_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Waitting'), (2, 'Accepted'), (3, 'Reject'), (4, 'Cancel'), (5, 'Success')], default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/tours/5'),
        ),
    ]
