# Generated by Django 3.1 on 2020-09-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_merge_20200831_1814'),
        ('travel', '0019_auto_20200903_0929'),
    ]

    operations = [
    ]
