# Generated by Django 3.1 on 2020-09-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_auto_20200903_1132'),
        ('travel', '0020_merge_20200903_1305'),
    ]

    operations = [
    ]
