# Generated by Django 3.0.8 on 2020-09-12 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_auto_20200911_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text=' Enter 1 - 5'),
        ),
    ]
