# Generated by Django 3.1 on 2020-09-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_auto_20200912_1920'),
        ('travel', '0021_merge_20200911_1343'),
    ]

    operations = [
    ]
