# Generated by Django 3.1 on 2020-09-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_merge_20200914_1622'),
        ('travel', '0024_merge_20200914_1313'),
    ]

    operations = [
    ]
